# Generated by Django 4.0.2 on 2022-02-13 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoodKind',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(max_length=128, verbose_name='種類')),
            ],
        ),
        migrations.CreateModel(
            name='FoodShop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop', models.CharField(max_length=128, verbose_name='お店')),
                ('description', models.TextField(blank=True, verbose_name='説明')),
                ('food_kind', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gohanbot.foodkind', verbose_name='種類')),
            ],
        ),
    ]
