# Generated by Django 4.0.2 on 2022-02-15 15:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("gohanbot", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="foodshop",
            name="created_by",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="投稿者",
            ),
            preserve_default=False,
        )
    ]
