# Generated by Django 4.0.2 on 2022-02-17 16:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gohanbot', '0002_foodshop_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodshop',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='とうこうしゃ'),
        ),
        migrations.AlterField(
            model_name='foodshop',
            name='description',
            field=models.TextField(blank=True, verbose_name='せつめい'),
        ),
        migrations.AlterField(
            model_name='foodshop',
            name='food_kind',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gohanbot.foodkind', verbose_name='しゅるい'),
        ),
        migrations.AlterField(
            model_name='foodshop',
            name='shop',
            field=models.CharField(max_length=128, verbose_name='おみせ'),
        ),
    ]
