# Generated by Django 4.0.3 on 2022-04-08 14:14
from django.core.management import call_command
from django.db import migrations


def load_fixture(apps, schema_editor):
    call_command("loaddata", "./fixture/food_kind.json", app_label="gohanbot")


class Migration(migrations.Migration):

    dependencies = [
        ("gohanbot", "0004_alter_foodkind_table_alter_foodshop_table")
    ]

    operations = [migrations.RunPython(load_fixture)]
