# Generated by Django 3.2 on 2022-04-08 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gohanbot', '0005_auto_20220408_2314'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='foodkind',
            table=None,
        ),
        migrations.AlterModelTable(
            name='foodshop',
            table=None,
        ),
    ]
