name: python_code_style
on:
  push:
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      # セットアップ
      - name: checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      - name: setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      # Pythonのコードスタイルを検証
      - name: install flake8
        run: pip install flake8
      - name: run flake8
        working-directory: .
        run: flake8
